name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build-db:
    runs-on: ubuntu-latest
    name: Build DB Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/db/Dockerfile
          push: true
          tags: alkrauss48/wordpress-starter-db:latest
  build-frontend:
    runs-on: ubuntu-latest
    name: Build Frontend Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/frontend/Dockerfile
          push: true
          tags: alkrauss48/wordpress-starter-frontend:latest
